service: aws-nodejs
frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-sam

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${file(./config/aws_params.yml):profile}
  stage: ${file(./config/aws_params.yml):stage}
  region: ${file(./config/aws_params.yml):region}
  deploymentBucket: ${file(./config/aws_params.yml):DEPLOYMENT_S3_BUCKET}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: alexdemo/show
          method: get
          cors: true
          integration: lambda

#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: ${file(./config/aws_params.yml):DEPLOYMENT_S3_BUCKET}
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
